### ISSUE TITLE
node-redscape help to install

### ISSUE THREAD

**Issue by pvdw0310** [playfultechnology/propcontrol#5]
I'am new to node red at I try to install node-redscape. 
Is there a step by step tutorial how to install this. 
I downloaded the flow but there where alot of errors and missing thing. So I did'nt know where to start.

Do I have to install first some libraries or palettes before I set your flow?

Many thanks to help.

**Comment by pvdw0310** [comment]
Hi, I'm find myself how to install the libraries and pallettes, and change the Mosca broker to Aedes broker.
The /ui dashboard I can see already, but now , how can I see the roomdisplay with the time and the hints on screen. 

What address do I have use in my browser to see the roomdisplay? I don't find a uibuilder name to use.
Thanks

**Comment by alastaira** [comment]
Hi! 
So, the flows.json file contained in the Node-RED directory is a kind of demonstration of all the possible features that you can make use of - it almost certainly will throw some errors if you try to run it "as-is", because you almost certainly won't have exactly the same hardware setup.

I'm planning revising quite a lot of this repository in the next few months but, in the meantime, I suggest you check out the wiki - which has code snippets for individual functionality that you can import.

**Comment by alastaira** [comment]
This is address by revised codebase.
